// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ACalendar: typeof import('ant-design-vue/es')['Calendar']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
